services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ssau-php
    volumes:
      - ./:/app
    working_dir: /app
  nginx:
    image: nginx:1.21.4-alpine
    container_name: ssau-nginx
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - 81:80
    working_dir: /app
  mysql:
    image: mysql:5.7.37
    container_name: ssau-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    working_dir: /app
